### ISSUE TITLE
Any chance to `require` and use as a JavaScript lib?

### ISSUE THREAD

**Issue by ghost** [DanielKRing1/Annoy.js#1]
Thanks a lot for this library @DanielKRing1 !
-----

I tried 
`const Annoy = require('annoy.js').default` but then with the same example in README I'm getting:

> C:\Users\user\Documents\classifier-ads-project\listings\node_modules\annoy.js\dist\components\AnnoyTree.js:124
>         if (p.length !== this.dimensions)
>               ^
> 
> TypeError: Cannot read properties of undefined (reading 'length')

I don't understand a lot with typeScript but... hopefully we are making it possible 😄

**Comment by ghost** [comment]
The error is maybe because of removed typeScript cast in the example:

```js
const Annoy = require('annoy.js').default
// 0. Define Annoy constants
const FOREST_SIZE = 5;
const MAX_LEAF_SIZE = 25

// 1. Init Annoy with constants
const a = new Annoy(FOREST_SIZE, MAX_LEAF_SIZE);

// 2. Fill Annoy forest with random points
const DIMENSIONS = 10;
const POINT_COUNT = 1;
console.log([...new Array(DIMENSIONS)].map(() => Math.random() * 40))
for (let i = 0; i < POINT_COUNT; i++) {
    const p = [...new Array(DIMENSIONS)].map(() => Math.random() * 40);
    a.add(p);
}

// 3. Query K Approximate Nearest Neighbors to a random point
const K = 100;
const randomPoint = [...new Array(DIMENSIONS)].map(() => Math.random() * 40);

const knn = a.get(
    randomPoint,
    K
);

// 4. Log results
console.log(knn);
```

I'm concluding this because 
https://github.com/DanielKRing1/Annoy.js/blob/dd5345ed09a26670a104db16ba0c71bc64925273/src/components/AnnoyTree.ts#L153

in my equivalent JS, there: 
`this.validatePoint(vd.vector);`

vd has no vector attribute, it is like the vector itself.

**Comment by DanielKRing1** [comment]
Wow, I'm surprised you're interested in the library...

My apologies. I never updated the ReadMe file after I updated the package to v2. I have made amendments to the ReadMe, and all should work now.

Copy the new ReadMe from this commit:

cf69c757e391b7acf84a350d1163ba5f3f3815d6

**Comment by DanielKRing1** [comment]
Here is the ReadMe example stripped of its Typescript syntax:

```
const Annoy = require('annoy.js').default;

// USING ANNOY TO QUERY K APPROXIMATE NEAREST NEIGHBORS

// 0. Define Annoy constants
const FOREST_SIZE = 10;
const MAX_LEAF_SIZE = 50;
const VECTOR_LEN = 10;

// 1. Init Annoy with constants
const a = new Annoy(FOREST_SIZE, VECTOR_LEN, MAX_LEAF_SIZE);

// 2. Generate random data points to add to the Annoy forest
const POINT_COUNT = 100000;
const dataPoints = [];
for (let i = 0; i < POINT_COUNT; i++) {
    const vector = [...new Array(VECTOR_LEN)].map(() => Math.random() * 40);

    const dp = {
        // Include a 'vector' property
        vector,
        // Add random data to the 'data' property
        data: i,
    };

    dataPoints.push(dp);
}

// 3. Fill Annoy forest with our data points
for (let i = 0; i < dataPoints.length; i++) {
    const dp = dataPoints[i];

    a.add(dp);
}

// 4. Query K Approximate Nearest Neighbors to a random point
const K = 20;
const p = [...new Array(VECTOR_LEN)].map(() => Math.random() * 40);
const knn = a.get(p, K);

// 5. Log our random query point and its K approximate nearest neighbors
console.log(p);
console.log(knn.length);

// ----

// SAVING/LOADING ANNOY TO/FROM A JSON OBJECT

// 1. Serialize to json
const asJson = a.toJson();
const asJsonStr = JSON.stringify(asJson);

// 2. Deserialize back to an Annoy instance
const rebuiltTree = new Annoy(FOREST_SIZE, VECTOR_LEN, MAX_LEAF_SIZE);
console.time('Rebuilt Annoy fromJson');
rebuiltTree.fromJson(asJsonStr);
console.timeEnd('Rebuilt Annoy fromJson');

// 3. Get KNN from rebuilt Annoy
console.time('Rebuilt Annoy KNN');
const rebuiltKnn = a.get(p, K);
console.timeEnd('Rebuilt Annoy KNN');
```

**Comment by ghost** [comment]
Hello @DanielKRing1 
Thank you for the follow up!!! Appreciate that.

Yes I'm trying to use it to get a simple words translations using data provided by Facebook muse. 

In fact this is maybe the only pure JS implementation here so .. 😃 

I will try the code provided the next few days and come back if anything raises..
Thanks a lot 😁

**Comment by ghost** [comment]
Thanks for the example!!

Without testing and without knowing the internals of the annoy index, I have a question, isn't it better to fill in directly?? From memory perspective?? 

for (let i = 0; i < POINT_COUNT; i++) {
   const vector = [...new Array(VECTOR_LEN)].map(() => Math.random() * 40); 
  const dp = {
 // Include a 'vector' property vector, // Add random data to the 'data' property data: i, };
 dataPoints.push(dp); 
} 
// 3. Fill Annoy forest with our data points 

for (let i = 0; i < dataPoints.length; i++) { const dp = dataPoints[i]; a.add(dp); }

**Comment by DanielKRing1** [comment]
Sorry for the late response... I think it's super cool that you're actually using my package, and yes, this is the only pure javascript implementation on npm, which is why I had to make it myself.

And you're right. It would be more memory efficient to feed the points directly into the Annoy object. I broke down the steps into 'Random point generation' then 'Filling the Annoy forest' bcus I thought it would make the example more clear.

**Comment by ghost** [comment]
I will test that today 😌
Thanks a lot for providing this!
I will come back with results as I will be feeding (little) big data 😄

**Comment by ghost** [comment]
I'm impressed !! it works like a charm, I will be back with benchmarks 

(check [this ](https://gist.github.com/bacloud22/63960c1720b41f04a20959f329b7cce4)! a mini and very approximate translator, clearly my example is a mess but I will clean up the gist later 🐵 )

Thanks again !
